# ============================================================== 
# Logging
# ==============================================================

[logging]
# Levels: DEBUG < INFO < WARNING < ERROR < CRITICAL
level = "DEBUG"     # Default root logger level = level of any logger without a specific override in [logging.levels]

[logging.levels]
# Per-module overrides (e.g. to increase verbosity for debugging / reduce it for noisy modules

"apm.control.cruise_control" = "INFO"
"apm.control.distance_control" = "INFO"
"apm.control.lane_keeper"  = "WARNING"
"apm.control.pid_controller" = "WARNING"
"apm.control.velocity_profiles" = "WARNING"

"apm.drivers.arduino" = "INFO"
"apm.drivers.camera.front" = "INFO"
"apm.drivers.camera.back" = "INFO"
"apm.drivers.gnss" = "INFO"

"apm.vision.frame_encoder" = "WARNING"
"apm.vision.line_detector" = "WARNING"

# ============================================================== 
# Cameras
# ==============================================================

[camera.front]
fps = 15                    # 15, 30, 60, 120
resolution = "SVGA"         # SVGA = 960x600 [pixels]
serial_number = 42146143    # 2.2mm big lens
record = false              # Save SVO video recordings to disk (at logs/recordings/front_YYYYMMDD_HHMMSS.svo)
display = false             # Convert frames to JPEG and stream to web app

[camera.front.depth]
enable = false              # Enable depth perception

[camera.front.body_tracking]
enable = false
detection_confidence = 40                  
#detection_model = "HUMAN_BODY_FAST"     # FAST, MEDIUM, ACCURATE


[camera.back]
fps = 15                    # 15, 30, 60, 120
resolution = "SVGA"         # SVGA = 960x600 [pixels]
serial_number = 40329509    # 4mm small lens
record = false              # Save SVO video recordings to disk (at logs/recordings/back_YYYYMMDD_HHMMSS.svo)
display = false             # Convert frames to JPEG and stream to web app

[camera.back.depth]
enable = false              # Enable depth perception

[camera.back.body_tracking]
enable = true
detection_confidence = 40
#detection_model = "HUMAN_BODY_FAST"    # FAST, MEDIUM, ACCURATE

# ============================================================== 
# Vision processing
# ==============================================================

[frame_encoding]
jpeg_quality = 80       # 0-100 (higher = better)
jpeg_scale = 0.5        # Fraction to scale down frames for display (e.g. in web app) to reduce bandwidth and CPU usage

[lane_detection]
canny_sigma = 0.33      # Standard deviation of Gaussian blur before edge detection (higher = more blur = fewer edges)
angle_threshold = 60    # [degrees] Max angle from vertical for a line to be considered a lane line
hough_threshold = 90    # Minimum Hough accumulator votes to accept a line.
mask_polygon = [[330, 172], [340, 399], [591, 399], [444, 172]] # Polygon to mask out battery box in preprocessed image
cut_top = 0.571         # fraction of image height to crop (4/7)
output_width = 640      # pixels to resize width to before lane detection (height is scaled proportionally)

# ============================================================== 
# Control parameters
# ==============================================================

[speed_model]
factor = 20.23       # m/s to PWM factor for default affine speed model
offset = 1540        # Neutral PWM value for 0 m/s
coefficients = [20.23, 1540] # Coefficients for polynomial speed model (starting with highest degree)

[lane_keeping]
cut_top = 0.571             # fraction of image height to crop (4/7)
angle_threshold = 50        # [degrees]
angle_setpoint = 90         # starting angle [deg] (0 = left, 90 = straight, 180 = right)
position_setpoint = 363     # pixels
set_width = 640             # pixels
show_lines = false          # Draw lane lines on the video stream (for display / debugging)

[lane_keeping.pid.angle]
kp = 0.9
ki = 0.0
kd = 0.06
beta = 1.0                  # Setpoint weighting for proportional term
gamma = 1.0                 # Setpoint weighting for derivative term

[lane_keeping.pid.position]
kp = 0.03
ki = 0.0
kd = 0.03
beta = 1.0                  # Setpoint weighting for proportional term
gamma = 1.0

[distance_control]
d_min = 2.0                 # [meters]
d_max = 6.0                 # [meters]

[distance_control.pid]
kp = 0.3
ki = 0.0
kd = 0.06
beta = 1.0                  # Setpoint weighting for proportional term
gamma = 0.1                 # Setpoint weighting for derivative term


# Velocity profile parameters
[velocity_profile.linear]
t_accel = 4.0               # [seconds] Time to reach target speed during linear acceleration

[velocity_profile.exponential]
alpha = 0.7                 # Higher alpha = faster acceleration

[velocity_profile.sigmoid]
k = 2.0                     # (1.5) Steepness: higher = faster transition through the middle
s = 3.0                     # (7) Inflection point: time at which the transition is at its midpoint

# PID parameters)
[pid.motor]
kp = 80.0                   # 80.0
ki = 1251.0                 # 1251.0
kd = 0.0                    # 0.0



# ============================================================== 
# GNSS
# ==============================================================

[gnss]
#device = "/dev/ttyACM0"
#baud_rate = 115200
measurement_rate = 10       # [Hz]
speed_threshold = 0.07      # m/s — minimum speed threshold to consider valid (to filter out noise when stationary)

# ============================================================== 
# Arduino
# ============================================================== 

[arduino.socket]
host = "192.168.56.1"       # IP address of APM's LAN interface
port = 49152                # Port number of APM's TCP server

[arduino.steer_angle]
neutral = 90
max_right = 45 # Max
max_left = 135 # Max

# Fallback affine speed model (v_hat = v_d * factor + neutral)
[arduino.speed_pwm] 
neutral = 1540
factor = 20.23 # Linear model to convert desired speed (m/s) to PWM (microsecond pulse width)

# ============================================================== 
# NiceGUI web app
# ============================================================== 
[webapp]
host = "0.0.0.0"
port = 8080